# -*- coding: utf-8 -*-
"""lab 7 test_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjX_ZrUzwWPQUg17rW_ikwBz6QMSGqmf
"""

import pytest
from app import divide_strict
def test_divide_exception_zero_divisor():
    """Test that divide_strict raises ValueError."""
    with pytest.raises(ValueError):
        divide_strict(5, 0)
def test_divide_exception_message():
    """Test that exception message is correct."""
    with pytest.raises(ValueError, match="Cannot divide"):
        divide_strict(10, 0)
@pytest.mark.parametrize("a, b", [
    (10, 0),
    (0, 0),
    (-5, 0),
])
def test_divide_exception_multiple(a, b):
    """Test exception with multiple inputs."""
    with pytest.raises(ValueError):
        divide_strict(a, b)

import pytest
from app import add, divide
@pytest.fixture
def numbers():
    """Fixture providing sample numbers."""
    return {"a": 10, "b": 5}
def test_add_with_fixture(numbers):
    """Test add function using fixture data."""
    result = add(numbers["a"], numbers["b"])
    assert result == 15
def test_divide_with_fixture(numbers):
    """Test divide function using fixture data."""
    result = divide(numbers["a"], numbers["b"])
    assert result == 2.0
@pytest.fixture
def sample_data():
    """Fixture for collection testing."""
    return [1, 2, 3, 4, 5]
def test_sum_with_fixture(sample_data):
    """Test sum function using fixture."""
    assert sum(sample_data) == 15
def test_count_with_fixture(sample_data):
    """Another test using the same fixture."""
    assert len(sample_data) == 5
@pytest.fixture
def calculator_numbers():
    """Fixture with setup and cleanup."""
    # Setup
    numbers = [10, 20, 30, 40, 50]
    print("\nSetting up test data...")
    yield numbers
    # Cleanup (runs after test)
    print("\nCleaning up test data...")
def test_with_setup_teardown(calculator_numbers):
    """Test that uses fixture with setup/teardown."""
    assert sum(calculator_numbers) == 150

def test_full_calculation_flow():
    """Test complete workflow: add then divide."""
    step1 = add(10, 5)
    assert step1 == 15
    final_result = divide(step1, 3)
    assert final_result == 5.0
def test_complex_workflow():
    """Test a more complex multi-step workflow."""
    step1 = add(50, 30)
    assert step1 == 80
    step2 = divide(step1, 2)
    assert step2 == 40.0
    step3 = divide(step2, 2)
    assert step3 == 20.0
def test_workflow_with_error_handling():
    """Test workflow that includes error handling."""
    result1 = add(100, 50)
    assert result1 == 150
    result2 = divide(result1, 0)
    assert result2 == "Error"
@pytest.fixture
def workflow_data():
    """Fixture for workflow tests."""
    return {
        "initial_a": 20,
        "initial_b": 10,
        "divisor": 5
    }
def test_workflow_with_fixture(workflow_data):
    """Functional test using fixture."""
    step1 = add(workflow_data["initial_a"],
                workflow_data["initial_b"])
    assert step1 == 30
    step2 = divide(step1, workflow_data["divisor"])
    assert step2 == 6.0