# -*- coding: utf-8 -*-
"""Lab 7 app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSXe3GhaH9SMwkC33hBdQCakH0Uz9uP_
"""

def add(a, b):
    """Add two numbers together."""
    return a + b
def divide(a, b):
    """Divide two numbers with error handling."""
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b
def is_even(n):
    """Check if a number is even."""
    return n % 2 == 0

def test_add_positive_numbers():
    """Test adding two positive numbers."""
    assert add(2, 3) == 5
def test_add_negative_and_positive():
    """Test adding a negative number and a positive number."""
    assert add(-1, 1) == 0
def test_add_negative_numbers():
    """Test adding two negative numbers."""
    assert add(-5, -3) == -8

def test_divide_normal():
    """Test normal division."""
    assert divide(10, 2) == 5
    assert divide(15, 3) == 5
    assert divide(100, 4) == 25
def test_divide_with_remainder():
    """Test division with remainder."""
    assert divide(10, 3) == 10/3
    assert divide(7, 2) == 3.5
def test_divide_by_zero():
    """Test division by zero (error case)."""
    try:
        divide(5, 0)
        assert False, "Expected ValueError for division by zero"
    except ValueError as e:
        assert str(e) == "Cannot divide by zero"
    try:
        divide(0, 0)
        assert False, "Expected ValueError for division by zero"
    except ValueError as e:
        assert str(e) == "Cannot divide by zero"

import pytest
@pytest.mark.parametrize("num, expected", [
    (2, True), # even number
    (3, False), # odd number
    (0, True), # zero is even
    (-4, True), # negative even
    (-7, False), # negative odd
    (100, True), # large even
])
def test_is_even(num, expected):
    """Test is_even function with multiple inputs."""
    assert is_even(num) == expected
@pytest.mark.parametrize("a, b, expected", [
    (10, 2, 5.0),
    (20, 4, 5.0),
    (7, 2, 3.5),
    (0, 5, 0.0),
])
def test_divide_parametrized(a, b, expected):
    """Test divide function with parametrized inputs."""
    assert divide(a, b) == expected

def divide_strict(a, b):
    """Divide with proper exception handling."""
    if b == 0:
        raise ValueError("Cannot divide by zero")
    return a / b